### ISSUE TITLE
 No image is shown in the token selection window of demo chat.

### ISSUE THREAD

**Issue by xjywhu** [dvlab-research/VisionZip#10]
After running the Demo-Chat code, I found there was no image shown in the selection token window. Maybe the "gradio_web_server.py" should be updated?
<img width="413" alt="image" src="https://github.com/user-attachments/assets/97cb222f-b1a0-4e13-ae85-e3354de9d6a0" />

**Comment by Yangsenqiao** [comment]
Hi,
Could you please review the following code?
[https://github.com/dvlab-research/VisionZip/blob/ccb20fe10082d41ee9d454e981d72ff63eda471d/llava/serve/gradio_web_server.py#L603](https://github.com/dvlab-research/VisionZip/blob/ccb20fe10082d41ee9d454e981d72ff63eda471d/llava/serve/gradio_web_server.py#L603)
After an image is uploaded, this line causes the image to also appear in the selection token window.


Best,
Senqiao

**Comment by xjywhu** [comment]
Many thanks for your help! This issue was caused by old version gradio, after updating the gradio version to 4.44.1, the selection token window shows the image.

**Comment by Yangsenqiao** [comment]
I am happy to see that your demo works well, and I will close this issue. If you have any questions, feel free to reopen it or add a new issue.😄
