### ISSUE TITLE
if r > 0:        ^^^^^ TypeError: '>' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by xjywhu** [dvlab-research/VisionZip#11]
![image](https://github.com/user-attachments/assets/23d1dda7-550d-4225-b3fa-2a5601d63a12)
  File "/home/xjy/VisionZip-main/visionzip/utils.py", line 124, in CLIP_EncoderLayer_forward
    if r > 0:
       ^^^^^
TypeError: '>' not supported between instances of 'list' and 'int'
 During running the code, I met the above error.

**Comment by xjywhu** [comment]
I have solved the issue. I changed ""r": [model.r]" to ""r": model.r".

![image](https://github.com/user-attachments/assets/07be9c99-14a2-46f5-85fd-87ab631680dd)

**Comment by Yangsenqiao** [comment]
I have re-run the current release code, and in my environment, no bugs were found.  
In my opinion, the final value of `r` during each forward pass is determined by the following line:  
[https://github.com/dvlab-research/VisionZip/blob/641be94a8337af06fe4889794adf81b3c12cf32c/visionzip/utils.py#L176](https://github.com/dvlab-research/VisionZip/blob/641be94a8337af06fe4889794adf81b3c12cf32c/visionzip/utils.py#L176).  

Anyway, I’m very glad to see your code running well. I’ll close this issue now, but if you have any further questions, feel free to reopen it or create a new issue.😄
