### ISSUE TITLE
Great Work! Ask for the Demo

### ISSUE THREAD

**Issue by BigDreamer11111** [dvlab-research/VisionZip#3]
Hi @Yangsenqiao ,

I’m Denny, a PhD student with a strong interest in Vision-Language Models. I found your demo particularly fascinating, especially its ability to interactively select visual tokens. I believe this feature could be incredibly useful for assessing the importance of different tokens.

Would you be able to share the code for the demo or provide guidance on how to develop a similar implementation?

Thank you in advance for your time and assistance!

Best regards,
Denny

**Comment by Yangsenqiao** [comment]
Hi Denny,

Thank you for your interest in our work! Since this demo involves some modifications to the LLaVA code itself, it may not be as straightforward or concise to release as VisionZip. Please kindly allow me some time to consider an appropriate release method.


Best,
Senqiao

**Comment by Yangsenqiao** [comment]
Hi Denny,

We have uploaded the demo code to the new branch, 'demo-chat'. :wave:

And the code is based on the [LLaVA](https://github.com/haotian-liu/LLaVA) framework with modifications. To help with analysis, we've provided the original unmodified LLaVA code in the commit 49b53a00dfd3a2d62ab79b8fdf5bc20d41b17ab9. You can compare this with the latest version to see the changes made.

I will close this issue. If you have any further questions, feel free to open a new issue or re-open this one. :blush:

Best,
Senqiao
