### ISSUE TITLE
Demo-Chat Code?

### ISSUE THREAD

**Issue by xjywhu** [dvlab-research/VisionZip#8]
Great work! It's a very good design for the Demo-Chat web, allowing users to choose the image token. Could you pls upload the Demo-Chat Web code in the repository?

**Comment by Yangsenqiao** [comment]
Hi @xjywhu 🤗,

We have uploaded the demo code to the new branch, 'demo-chat'. :wave:

And the code is based on the [LLaVA](https://github.com/haotian-liu/LLaVA) framework with modifications. To help with analysis, we've provided the original unmodified LLaVA code in the commit 49b53a00dfd3a2d62ab79b8fdf5bc20d41b17ab9. You can compare this with the latest version to see the changes made.

I will close this issue. If you have any further questions, feel free to open a new issue or re-open this one. :blush:

Best,
Senqiao

**Comment by xjywhu** [comment]
Hi Senqiao:
Great! Many thanks for your demo code!
Best,
Jingyu

**Comment by Yangsenqiao** [comment]
Hi Jingyu,

Thank you for your kind words. I hope VisionZip will be helpful for your research.

Best,
Senqiao
